import { Global, Module } from '@nestjs/common';
import { DatabaseModule } from '@database';
import { uicProviders } from '@uic/providers';
import {
  CatalogueController,
  ModalitiesController,
  RequirementsController,
  ProjectPlansController,
  PlanningsController,
  EventsController,
  ProjectsController,
  EnrollmentsController,
  StudentsController,
  StudentInformationsController,
  RequirementRequestsController,
  MeshStudentRequirementsController,
  TutorAssignmentsController,
  EstudiantesController,
  TribunalsController,
  ComplexivosController,
  TeachersController,
  StudentsDegreeController,
  RequirementFormatsController,
  CatalogueTypesController,
  ProfessionsController,
  DocumentsController,
  //YearsController,
  InscriptionsController,
  ResponsibleTutorsController,
  CoodinatorsController,
  FormatsController,
  DownloadFormatsController,
  UploadScoresController,
  PreparationCoursesController,
  UploadProjectsController,
  TheoricalNotesController,
  CaseViewsController,
  RubricsController,
  ComplexTimelinesController,
  NotesController,
  PracticalCasesController,
  ItemsController,
  RatingWeightsController,
  MemorandumsController,
  MemorandumTutorsController,
  ScheduleActivitiesController,
  TotalNotesController,
  ProjectBenchsController,
  NoteSettingsController,
  NoteDefensesController,
  DefenseApprovedsController,
  TotalCasesController,
  IndividualDefensesController,

} from '@uic/controllers';
import {
  ModalitiesService,
  ProjectPlansService,
  RequirementsService,
  CatalogueService,
  CoordinatorsService,
  PlanningsService,
  EventsService,
  TutorAssignmentsService,
  ProjectsService,
  EnrollmentsService,
  StudentInformationsService,
  RequirementRequestsService,
  MeshStudentRequirementsService,
  EstudiantesService,
  TribunalsService,
  NotesService,
  ComplexivosService,
  TeachersService,
  StudentsDegreeService,
  RequirementFormatsService,
  ProfessionsService,
  CatalogueTypeService,
  DocumentsService,
  //YearsService,
  SignaturesService,
  InscriptionsService,
  ResponsibleTutorsService,
  FormatsService,
  DownloadFormatsService,
  UploadScoresService,
  PreparationCoursesService,
  UploadProjectsService,
  TheoricalNotesService,
  CourtProjectsService,
  CaseViewsService,
  RubricsService,
  ComplexTimelinesService,
  PracticalCasesService,
  ItemsService,
  ComplexSchedulesService,
  RatingWeightsService,
  MemorandumsService,
  MemorandumTutorsService,
  ScheduleActivitiesService,
  TotalNotesService,
  ProjectBenchsService,
  NoteSettingsService,
  NoteDefensesService,
  DefenseApprovedsService,
  TotalCasesService,
  IndividualDefensesService,
  
} from '@uic/services';
import { MemoryStoredFile, NestjsFormDataModule } from 'nestjs-form-data';
import { ResponseProjectPlansService } from './services/response-project-plan.service';
import { ResponseProjectPlansController } from './controllers/response-project-plans.controller';
import { UploadRequirementRequestsController } from './controllers/upload-requirement-requests.controller';
import { UploadRequirementRequestsService } from './services/upload-requirement-requests.service';
import { ReviewRequirementsService } from './services/review-requirements.service';
import { ReviewRequirementsController } from './controllers/review-requirements.controller';
import { SignaturesController } from './controllers/signatures.controller';
import { CourtProjectsController } from './controllers/court-project.controller';
import { AttendanceRecordController } from './controllers/attendance-record.controller';
import { AttendanceRecordService } from './services/attendance-record.service';
import { EvaluationController } from './controllers/evaluation.controller';
import { EvaluationService } from './services/evaluation.service';
import { EvaluationDateController } from './controllers/evaluation-date.controller';
import { EvaluationDateService } from './services/evaluation-date.service';
import { ComplexSchedulesController } from './controllers/complex-schedule.controller';
import { RubricNotesService } from './services/rubric-note.service';
import { RubricNotesController } from './controllers/rubric-note.controller';

@Global()
@Module({
  imports: [
    DatabaseModule,
    NestjsFormDataModule.config({
      storage: MemoryStoredFile,
    }),
  ],
  controllers: [
    CatalogueController,
    ProjectPlansController,
    ModalitiesController,
    RequirementsController,
    PlanningsController,
    EventsController,
    TutorAssignmentsController,
    ProjectsController,
    ResponseProjectPlansController,
    EnrollmentsController,
    //StudentsController,
    StudentInformationsController,
    RequirementRequestsController,
    RequirementFormatsController,
    MeshStudentRequirementsController,
    EstudiantesController,
    TribunalsController,
    NotesController,
    ComplexivosController,
    TeachersController,
    StudentsDegreeController,
    ProfessionsController,
    CatalogueTypesController,
    DocumentsController,
    //YearsController,
    SignaturesController,
    InscriptionsController,
    ResponsibleTutorsController,
    CoodinatorsController,
    FormatsController,
    DownloadFormatsController,
    UploadRequirementRequestsController,
    ReviewRequirementsController,
    UploadScoresController,
    PreparationCoursesController,
    UploadProjectsController,
    TheoricalNotesController,
    CourtProjectsController,
    AttendanceRecordController,
    EvaluationController,
    CaseViewsController,
    RubricsController,
    EvaluationDateController,
    ComplexTimelinesController,
    ComplexSchedulesController,
    PracticalCasesController,
    ItemsController,
    RatingWeightsController,
    MemorandumsController,
    MemorandumTutorsController,
    ScheduleActivitiesController,
    TotalNotesController,
    ProjectBenchsController,
    RubricNotesController,
    NoteSettingsController,
    NoteDefensesController,
    DefenseApprovedsController,
    TotalCasesController,
    IndividualDefensesController
  
  ],
  providers: [
    ...uicProviders,
    PlanningsService,
    RequirementsService,
    ModalitiesService,
    ProjectPlansService,
    CatalogueService,
    EventsService,
    TutorAssignmentsService,
    ProjectsService,
    ResponseProjectPlansService,
    EnrollmentsService,
    //StudentsService,
    StudentInformationsService,
    RequirementRequestsService,
    RequirementFormatsService,
    MeshStudentRequirementsService,
    EstudiantesService,
    TribunalsService,
    NotesService,
    ComplexivosService,
    TeachersService,
    StudentsDegreeService,
    ProfessionsService,
    CatalogueTypeService,
    DocumentsService,
    //YearsService,
    SignaturesService,
    InscriptionsService,
    ResponsibleTutorsService,
    CoordinatorsService,
    FormatsService,
    DownloadFormatsService,
    UploadRequirementRequestsService,
    ReviewRequirementsService,
    UploadScoresService,
    PreparationCoursesService,
    UploadProjectsService,
    TheoricalNotesService,
    CourtProjectsService,
    AttendanceRecordService,
    EvaluationService,
    CaseViewsService,
    RubricsService,
    EvaluationDateService,
    ComplexTimelinesService,
    ComplexSchedulesService,
    PracticalCasesService,
    ItemsService,
    RatingWeightsService,
    MemorandumsService,
    MemorandumTutorsService,
    ScheduleActivitiesService,
    TotalNotesService,
    ProjectBenchsService,
    RubricNotesService,
    NoteSettingsService,
    NoteDefensesService,
    DefenseApprovedsService,
    TotalCasesService,
    IndividualDefensesService
  ],
  exports: [],
})
export class UicModule {}
